project:
  type: website

website:
  title: "Singapore's rental market"
  navbar:
    left:
    - text: "Proposal"
      href: "Group Project/Proposal.html"
    
    - text: "Poster"
      href: "Group Project/poster.html"

    - text: "Shiny App"
      href: "Group Project/Shinyapp"

    - text: "User-Guide"
      href: "Group Project/userguide"

          
    right:
      - href: index.qmd
        text: home
      - about.qmd
        
     
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual
